source:
  enabled: true
  rlcp: true
  name_template: "{{ .ProjectName }}-{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: "{{ tolower .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/hibare/GPGDecryptor/internal/version.CurrentVersion={{.Version}}

universal_binaries:
  - replace: true
    name_template: "{{ tolower .ProjectName }}"

nfpms:
  - id: nfpms
    package_name: "gpgdecryptor"
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Hibare.
    homepage: https://github.com/hibare/GPGDecryptor
    maintainer: Hibare <admin@hibare.in>.
    description: |-
      Utility to decrypt GPG encrypted files.
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: 
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all
    
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

publishers:
  - name: fury.io
    ids:
      - nfpms
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/hibare/
