name: Test, Build & Publish

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
      - "**/.github"
      - "**/.vscode"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-build-publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Goreleaser
        uses: hibare/.github/github/shared-workflows/goreleaser@3f2aca66510c1847daef4967f5ece127f648292b # v0.4.0
        with:
          args: ${{ github.event_name == 'pull_request' && 'build --snapshot --clean' || 'release --clean' }}
          sign: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}